default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  username: 'friendpod'
  password: 'friendpod'
  pool: 5

development:
  <<: *default
  database: friendpod_development

test:
  <<: *default
  database: friendpod_test

production:
  <<: *default
  database: friendpod_production
  username: friendpod
  password: <%= ENV['FRIENDPOD_DATABASE_PASSWORD'] %>
