default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  username: 'friendpod'
  password: 'friendpod'
  pool: 5

development:
  <<: *default
  database: friendpod_development

test:
  <<: *default
  database: friendpod_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
